### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by abenrob**
pricing for Targomo API has moved to the API documentation pages. Thanks!

### CODE REVIEW

**Review by cwthom — CHANGES_REQUESTED** [review]
Hi @abenrob , thanks for this! Can you make the edit in README.Rmd rather than README.md?
Thanks!

**Comment by cwthom** [comment]
Hi @abenrob, if you feel like being really helpful... I think some of the other links in the README are also out of date (the list of 3 services for example). Any chance you could check? :)

**Comment by abenrob** [comment]
> Hi @abenrob, if you feel like being really helpful... I think some of the other links in the README are also out of date (the list of 3 services for example). Any chance you could check? :)

Moved changed to `.Rmd`, updated all identified links.

**Review by cwthom — APPROVED** [review]
Brilliant, thanks very much!

**Pull request merged**
